apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: golden-path-templates
  description: A collection of all Golden Path templates
spec:
  targets:
    - ./templates/spring-boot-rest-service/template.yaml
    - ./templates/create-react-app/template.yaml
    - ./templates/docs-template/template.yaml