apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: crewpro-tech-team
  description: CrewPro Tech Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: crewprotechteam@pstechnology.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: crewpro-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sunilm
spec:
  profile:
    displayName: Sunil Mamilla
    email: sunil.mamilla@pstechnology.com
    picture: https://www.gravatar.com/avatar/ced2f20e9e995cc4566fcee9640d7aac?s=800&d=identicon
  memberOf: [crewpro-tech-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rajd
spec:
  profile:
    displayName: Raj Dhandapani
    email: raj.dhandapani@pstechnology.com
    picture: https://www.gravatar.com/avatar/ced2f20e9e995cc4566fcee9640d7aac?s=800&d=identicon
  memberOf: [crewpro-tech-team]
