apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/source-location: url:http://pst-gitlab.pstechnology.com/crewpro/employeetracking/documents/blob/master/Design/Business
      Service Definitions/Do Not Use - Tracking.yaml
  description: The User shall be able to track an employee on a position based on
    certrain conditions during DecisionFill, Call/Vacate, Lay-off on call and Deadhead.
  name: Track_an_Employee_on_an_Assignment_API_-1.0.0
spec:
  definition:
    $text: http://pst-gitlab.pstechnology.com/crewpro/employeetracking/documents/blob/master/Design/Business
      Service Definitions/Do Not Use - Tracking.yaml
  lifecycle: production
  owner: crewpro-tech-team
  system: EmployeeTracking
  type: openapi
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/source-location: url:http://pst-gitlab.pstechnology.com/crewpro/employeetracking/documents/blob/master/Design/Business
      Service Definitions/EmployeeTracking.yaml
  description: The System will use these APIs to manage non-work/employee tracking
  name: Non_Work_Tracking_API_-1.0.0
spec:
  definition:
    $text: http://pst-gitlab.pstechnology.com/crewpro/employeetracking/documents/blob/master/Design/Business
      Service Definitions/EmployeeTracking.yaml
  lifecycle: production
  owner: crewpro-tech-team
  system: EmployeeTracking
  type: openapi
