apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  description: ${{values.description | dump}}
  tags:
    - bindings
  annotations:
    github.com/project-slug: ${{values.project_slug}}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner}}
  system: ${{values.system}}
  consumesApis: [${{values.cataloged_api | dump}}]
