name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Containerize
        run: mvn spring-boot:build-image 
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-Artifacts
          path: target/*
      # Publish to JFrog Artifactory https://github.com/jfrog/project-examples/tree/e19594f315c9fd250ee29cc722bd54301655704c/github-action-examples
