name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode -Dapi_spec_location_bearer_token=${{ secrets.API_REPO_READ_BEARER_TOKEN }} --update-snapshots package
      - name: Upload Jars
        uses: actions/upload-artifact@v3
        with:
          name: Maven-Artifacts
          path: target/*.jar
      # Publish to JFrog Artifactory https://github.com/jfrog/project-examples/tree/e19594f315c9fd250ee29cc722bd54301655704c/github-action-examples