apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: crewpro-api-bindings-template
  title: CrewPro API bindings
  description: Generates api-bindings project from API specification
  tags:
    - recommended
    - java-17
    - maven
    - api-bindings
    - crewpro
spec:
  owner: group:up-pst/cnx-pst-team
  type: component

  parameters:
    - title: Provide some simple information
      required:
        - component_group_id
        - owner
        - api
      properties:
        component_group_id:
          title: Group Name
          type: string
          description: Group this component belongs to
          default: com.pst.app.crewpro.api.bindings
          enum:
            - com.pst.api.bindings
            - com.pst.app.crewpro.api.bindings
          enumNames:
            - "PST"
            - "PST CrewPro"
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: up-pst/cnx-pst-team
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        api:
          title: API
          type: string
          description: API for which bindings will be generated
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              - kind: API
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedOwners: ["UP-PST"]
            allowedHosts: ["github.com"]

  steps:
    # https://github.com/backstage/backstage/issues/17053
    - id: catalogFetch
      name: Fetch Context
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.api }}

    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          group_id: ${{ parameters.component_group_id }}
          component_id: ${{ steps['catalogFetch'].output.entity.metadata.name | trim | lower | replace("_", "-") | replace(".", "_")}}-bindings
          api_spec_location:  ${{ steps['catalogFetch'].output.entity.metadata.annotations | pick('backstage.io/source-location') | replace("url:", "") }}
          java_package_name: ${{ parameters.component_group_id }}.${{ steps['catalogFetch'].output.entity.metadata.name | trim | lower | replace("-", "_") }}
          owner: ${{ parameters.owner }}
          system: ${{ steps['catalogFetch'].output.entity.spec.system }}
          source_control_url: ${{ parameters.repoUrl | parseRepoUrl }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          cataloged_api: ${{ parameters.api }}
          description: ${{ steps['catalogFetch'].output.entity.metadata.name | trim | lower | replace("_", "-") | replace(".", "_")}} API Bindings

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: API Bindings for ${{ steps['catalogFetch'].output.entity.metadata.name }}
        repoUrl: ${{ parameters.repoUrl }}
        # Remove if you want it to be master, all public repos have pivoted to main as the default branch now
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
